[package]
name = "tonex-midi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tonex-application = { path = "../tonex-application", version = "0.1.0" }
tonex-domain = { path = "../tonex-domain", version = "0.1.0" }
tonex-parameters = { path = "../tonex-parameters", version = "0.1.0" }

[lints]
workspace = true
