// @generated by tools/generate-tonex-parameters.py; do not edit.
pub const PARAMETER_COUNT: u16 = 109;
pub const GLOBAL_FIRST: u16 = 110;
pub const GLOBAL_END: u16 = 117;

pub const TONEX_PARAM_NOISE_GATE_POST: ParameterId = ParameterId::from_generated(0);
pub const TONEX_PARAM_NOISE_GATE_ENABLE: ParameterId = ParameterId::from_generated(1);
pub const TONEX_PARAM_NOISE_GATE_THRESHOLD: ParameterId = ParameterId::from_generated(2);
pub const TONEX_PARAM_NOISE_GATE_RELEASE: ParameterId = ParameterId::from_generated(3);
pub const TONEX_PARAM_NOISE_GATE_DEPTH: ParameterId = ParameterId::from_generated(4);
pub const TONEX_PARAM_COMP_POST: ParameterId = ParameterId::from_generated(5);
pub const TONEX_PARAM_COMP_ENABLE: ParameterId = ParameterId::from_generated(6);
pub const TONEX_PARAM_COMP_THRESHOLD: ParameterId = ParameterId::from_generated(7);
pub const TONEX_PARAM_COMP_MAKE_UP: ParameterId = ParameterId::from_generated(8);
pub const TONEX_PARAM_COMP_ATTACK: ParameterId = ParameterId::from_generated(9);
pub const TONEX_PARAM_EQ_POST: ParameterId = ParameterId::from_generated(10);
pub const TONEX_PARAM_EQ_BASS: ParameterId = ParameterId::from_generated(11);
pub const TONEX_PARAM_EQ_BASS_FREQ: ParameterId = ParameterId::from_generated(12);
pub const TONEX_PARAM_EQ_MID: ParameterId = ParameterId::from_generated(13);
pub const TONEX_PARAM_EQ_MIDQ: ParameterId = ParameterId::from_generated(14);
pub const TONEX_PARAM_EQ_MID_FREQ: ParameterId = ParameterId::from_generated(15);
pub const TONEX_PARAM_EQ_TREBLE: ParameterId = ParameterId::from_generated(16);
pub const TONEX_PARAM_EQ_TREBLE_FREQ: ParameterId = ParameterId::from_generated(17);
pub const TONEX_PARAM_MODEL_AMP_ENABLE: ParameterId = ParameterId::from_generated(18);
pub const TONEX_PARAM_MODEL_SW1: ParameterId = ParameterId::from_generated(19);
pub const TONEX_PARAM_MODEL_GAIN: ParameterId = ParameterId::from_generated(20);
pub const TONEX_PARAM_MODEL_VOLUME: ParameterId = ParameterId::from_generated(21);
pub const TONEX_PARAM_MODEX_MIX: ParameterId = ParameterId::from_generated(22);
pub const TONEX_PARAM_CABINET_UNKNOWN: ParameterId = ParameterId::from_generated(23);
pub const TONEX_PARAM_CABINET_TYPE: ParameterId = ParameterId::from_generated(24);
pub const TONEX_PARAM_VIR_CABINET_MODEL: ParameterId = ParameterId::from_generated(25);
pub const TONEX_PARAM_VIR_RESO: ParameterId = ParameterId::from_generated(26);
pub const TONEX_PARAM_VIR_MIC_1: ParameterId = ParameterId::from_generated(27);
pub const TONEX_PARAM_VIR_MIC_1_X: ParameterId = ParameterId::from_generated(28);
pub const TONEX_PARAM_VIR_MIC_1_Z: ParameterId = ParameterId::from_generated(29);
pub const TONEX_PARAM_VIR_MIC_2: ParameterId = ParameterId::from_generated(30);
pub const TONEX_PARAM_VIR_MIC_2_X: ParameterId = ParameterId::from_generated(31);
pub const TONEX_PARAM_VIR_MIC_2_Z: ParameterId = ParameterId::from_generated(32);
pub const TONEX_PARAM_VIR_BLEND: ParameterId = ParameterId::from_generated(33);
pub const TONEX_PARAM_MODEL_PRESENCE: ParameterId = ParameterId::from_generated(34);
pub const TONEX_PARAM_MODEL_DEPTH: ParameterId = ParameterId::from_generated(35);
pub const TONEX_PARAM_REVERB_POSITION: ParameterId = ParameterId::from_generated(36);
pub const TONEX_PARAM_REVERB_ENABLE: ParameterId = ParameterId::from_generated(37);
pub const TONEX_PARAM_REVERB_MODEL: ParameterId = ParameterId::from_generated(38);
pub const TONEX_PARAM_REVERB_SPRING1_TIME: ParameterId = ParameterId::from_generated(39);
pub const TONEX_PARAM_REVERB_SPRING1_PREDELAY: ParameterId = ParameterId::from_generated(40);
pub const TONEX_PARAM_REVERB_SPRING1_COLOR: ParameterId = ParameterId::from_generated(41);
pub const TONEX_PARAM_REVERB_SPRING1_MIX: ParameterId = ParameterId::from_generated(42);
pub const TONEX_PARAM_REVERB_SPRING2_TIME: ParameterId = ParameterId::from_generated(43);
pub const TONEX_PARAM_REVERB_SPRING2_PREDELAY: ParameterId = ParameterId::from_generated(44);
pub const TONEX_PARAM_REVERB_SPRING2_COLOR: ParameterId = ParameterId::from_generated(45);
pub const TONEX_PARAM_REVERB_SPRING2_MIX: ParameterId = ParameterId::from_generated(46);
pub const TONEX_PARAM_REVERB_SPRING3_TIME: ParameterId = ParameterId::from_generated(47);
pub const TONEX_PARAM_REVERB_SPRING3_PREDELAY: ParameterId = ParameterId::from_generated(48);
pub const TONEX_PARAM_REVERB_SPRING3_COLOR: ParameterId = ParameterId::from_generated(49);
pub const TONEX_PARAM_REVERB_SPRING3_MIX: ParameterId = ParameterId::from_generated(50);
pub const TONEX_PARAM_REVERB_SPRING4_TIME: ParameterId = ParameterId::from_generated(51);
pub const TONEX_PARAM_REVERB_SPRING4_PREDELAY: ParameterId = ParameterId::from_generated(52);
pub const TONEX_PARAM_REVERB_SPRING4_COLOR: ParameterId = ParameterId::from_generated(53);
pub const TONEX_PARAM_REVERB_SPRING4_MIX: ParameterId = ParameterId::from_generated(54);
pub const TONEX_PARAM_REVERB_ROOM_TIME: ParameterId = ParameterId::from_generated(55);
pub const TONEX_PARAM_REVERB_ROOM_PREDELAY: ParameterId = ParameterId::from_generated(56);
pub const TONEX_PARAM_REVERB_ROOM_COLOR: ParameterId = ParameterId::from_generated(57);
pub const TONEX_PARAM_REVERB_ROOM_MIX: ParameterId = ParameterId::from_generated(58);
pub const TONEX_PARAM_REVERB_PLATE_TIME: ParameterId = ParameterId::from_generated(59);
pub const TONEX_PARAM_REVERB_PLATE_PREDELAY: ParameterId = ParameterId::from_generated(60);
pub const TONEX_PARAM_REVERB_PLATE_COLOR: ParameterId = ParameterId::from_generated(61);
pub const TONEX_PARAM_REVERB_PLATE_MIX: ParameterId = ParameterId::from_generated(62);
pub const TONEX_PARAM_MODULATION_POST: ParameterId = ParameterId::from_generated(63);
pub const TONEX_PARAM_MODULATION_ENABLE: ParameterId = ParameterId::from_generated(64);
pub const TONEX_PARAM_MODULATION_MODEL: ParameterId = ParameterId::from_generated(65);
pub const TONEX_PARAM_MODULATION_CHORUS_SYNC: ParameterId = ParameterId::from_generated(66);
pub const TONEX_PARAM_MODULATION_CHORUS_TS: ParameterId = ParameterId::from_generated(67);
pub const TONEX_PARAM_MODULATION_CHORUS_RATE: ParameterId = ParameterId::from_generated(68);
pub const TONEX_PARAM_MODULATION_CHORUS_DEPTH: ParameterId = ParameterId::from_generated(69);
pub const TONEX_PARAM_MODULATION_CHORUS_LEVEL: ParameterId = ParameterId::from_generated(70);
pub const TONEX_PARAM_MODULATION_TREMOLO_SYNC: ParameterId = ParameterId::from_generated(71);
pub const TONEX_PARAM_MODULATION_TREMOLO_TS: ParameterId = ParameterId::from_generated(72);
pub const TONEX_PARAM_MODULATION_TREMOLO_RATE: ParameterId = ParameterId::from_generated(73);
pub const TONEX_PARAM_MODULATION_TREMOLO_SHAPE: ParameterId = ParameterId::from_generated(74);
pub const TONEX_PARAM_MODULATION_TREMOLO_SPREAD: ParameterId = ParameterId::from_generated(75);
pub const TONEX_PARAM_MODULATION_TREMOLO_LEVEL: ParameterId = ParameterId::from_generated(76);
pub const TONEX_PARAM_MODULATION_PHASER_SYNC: ParameterId = ParameterId::from_generated(77);
pub const TONEX_PARAM_MODULATION_PHASER_TS: ParameterId = ParameterId::from_generated(78);
pub const TONEX_PARAM_MODULATION_PHASER_RATE: ParameterId = ParameterId::from_generated(79);
pub const TONEX_PARAM_MODULATION_PHASER_DEPTH: ParameterId = ParameterId::from_generated(80);
pub const TONEX_PARAM_MODULATION_PHASER_LEVEL: ParameterId = ParameterId::from_generated(81);
pub const TONEX_PARAM_MODULATION_FLANGER_SYNC: ParameterId = ParameterId::from_generated(82);
pub const TONEX_PARAM_MODULATION_FLANGER_TS: ParameterId = ParameterId::from_generated(83);
pub const TONEX_PARAM_MODULATION_FLANGER_RATE: ParameterId = ParameterId::from_generated(84);
pub const TONEX_PARAM_MODULATION_FLANGER_DEPTH: ParameterId = ParameterId::from_generated(85);
pub const TONEX_PARAM_MODULATION_FLANGER_FEEDBACK: ParameterId = ParameterId::from_generated(86);
pub const TONEX_PARAM_MODULATION_FLANGER_LEVEL: ParameterId = ParameterId::from_generated(87);
pub const TONEX_PARAM_MODULATION_ROTARY_SYNC: ParameterId = ParameterId::from_generated(88);
pub const TONEX_PARAM_MODULATION_ROTARY_TS: ParameterId = ParameterId::from_generated(89);
pub const TONEX_PARAM_MODULATION_ROTARY_SPEED: ParameterId = ParameterId::from_generated(90);
pub const TONEX_PARAM_MODULATION_ROTARY_RADIUS: ParameterId = ParameterId::from_generated(91);
pub const TONEX_PARAM_MODULATION_ROTARY_SPREAD: ParameterId = ParameterId::from_generated(92);
pub const TONEX_PARAM_MODULATION_ROTARY_LEVEL: ParameterId = ParameterId::from_generated(93);
pub const TONEX_PARAM_DELAY_POST: ParameterId = ParameterId::from_generated(94);
pub const TONEX_PARAM_DELAY_ENABLE: ParameterId = ParameterId::from_generated(95);
pub const TONEX_PARAM_DELAY_MODEL: ParameterId = ParameterId::from_generated(96);
pub const TONEX_PARAM_DELAY_DIGITAL_SYNC: ParameterId = ParameterId::from_generated(97);
pub const TONEX_PARAM_DELAY_DIGITAL_TS: ParameterId = ParameterId::from_generated(98);
pub const TONEX_PARAM_DELAY_DIGITAL_TIME: ParameterId = ParameterId::from_generated(99);
pub const TONEX_PARAM_DELAY_DIGITAL_FEEDBACK: ParameterId = ParameterId::from_generated(100);
pub const TONEX_PARAM_DELAY_DIGITAL_MODE: ParameterId = ParameterId::from_generated(101);
pub const TONEX_PARAM_DELAY_DIGITAL_MIX: ParameterId = ParameterId::from_generated(102);
pub const TONEX_PARAM_DELAY_TAPE_SYNC: ParameterId = ParameterId::from_generated(103);
pub const TONEX_PARAM_DELAY_TAPE_TS: ParameterId = ParameterId::from_generated(104);
pub const TONEX_PARAM_DELAY_TAPE_TIME: ParameterId = ParameterId::from_generated(105);
pub const TONEX_PARAM_DELAY_TAPE_FEEDBACK: ParameterId = ParameterId::from_generated(106);
pub const TONEX_PARAM_DELAY_TAPE_MODE: ParameterId = ParameterId::from_generated(107);
pub const TONEX_PARAM_DELAY_TAPE_MIX: ParameterId = ParameterId::from_generated(108);
pub const TONEX_PARAM_LAST: u16 = 109;
pub const TONEX_GLOBAL_BPM: ParameterId = ParameterId::from_generated(110);
pub const TONEX_GLOBAL_INPUT_TRIM: ParameterId = ParameterId::from_generated(111);
pub const TONEX_GLOBAL_CABSIM_BYPASS: ParameterId = ParameterId::from_generated(112);
pub const TONEX_GLOBAL_TEMPO_SOURCE: ParameterId = ParameterId::from_generated(113);
pub const TONEX_GLOBAL_TUNING_REFERENCE: ParameterId = ParameterId::from_generated(114);
pub const TONEX_GLOBAL_BYPASS: ParameterId = ParameterId::from_generated(115);
pub const TONEX_GLOBAL_MASTER_VOLUME: ParameterId = ParameterId::from_generated(116);

pub(crate) const SPECS: [ParameterSpec; 116] = [
    ParameterSpec {
        id: TONEX_PARAM_NOISE_GATE_POST,
        label: "NG POST",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_NOISE_GATE_ENABLE,
        label: "NG POWER",
        kind: ParameterKind::Switch,
        default: 1_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_NOISE_GATE_THRESHOLD,
        label: "NG THRESH",
        kind: ParameterKind::Range,
        default: -64_f32,
        minimum: -100_f32,
        maximum: 0_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_NOISE_GATE_RELEASE,
        label: "NG REL",
        kind: ParameterKind::Range,
        default: 20_f32,
        minimum: 5_f32,
        maximum: 500_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_NOISE_GATE_DEPTH,
        label: "NG DEPTH",
        kind: ParameterKind::Range,
        default: -60_f32,
        minimum: -100_f32,
        maximum: -20_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_COMP_POST,
        label: "COMP POST",
        kind: ParameterKind::Switch,
        default: 1_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_COMP_ENABLE,
        label: "COMP POWER",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_COMP_THRESHOLD,
        label: "COMP THRESH",
        kind: ParameterKind::Range,
        default: -14_f32,
        minimum: -40_f32,
        maximum: 0_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_COMP_MAKE_UP,
        label: "COMP GAIN",
        kind: ParameterKind::Range,
        default: -12_f32,
        minimum: -30_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_COMP_ATTACK,
        label: "COMP ATTACK",
        kind: ParameterKind::Range,
        default: 14_f32,
        minimum: 1_f32,
        maximum: 51_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_EQ_POST,
        label: "EQ POST",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_EQ_BASS,
        label: "EQ BASS",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_EQ_BASS_FREQ,
        label: "EQ BFREQ",
        kind: ParameterKind::Range,
        default: 300_f32,
        minimum: 75_f32,
        maximum: 600_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_EQ_MID,
        label: "EQ MID",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_EQ_MIDQ,
        label: "EQ MIDQ",
        kind: ParameterKind::Range,
        default: 0.7_f32,
        minimum: 0.2_f32,
        maximum: 3.0_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_EQ_MID_FREQ,
        label: "EQ MFREQ",
        kind: ParameterKind::Range,
        default: 750_f32,
        minimum: 150_f32,
        maximum: 5000_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_EQ_TREBLE,
        label: "EQ TREBLE",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_EQ_TREBLE_FREQ,
        label: "EQ TFREQ",
        kind: ParameterKind::Range,
        default: 1900_f32,
        minimum: 1000_f32,
        maximum: 4000_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODEL_AMP_ENABLE,
        label: "MDL AMP",
        kind: ParameterKind::Switch,
        default: 1_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODEL_SW1,
        label: "MDL SW1",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODEL_GAIN,
        label: "MDL GAIN",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODEL_VOLUME,
        label: "MDL VOL",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODEX_MIX,
        label: "MDL MIX",
        kind: ParameterKind::Range,
        default: 100_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_CABINET_UNKNOWN,
        label: "MDL CABU",
        kind: ParameterKind::Switch,
        default: 1_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_CABINET_TYPE,
        label: "MDL CAB",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 2_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_VIR_CABINET_MODEL,
        label: "VIR_CMDL",
        kind: ParameterKind::Select,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_VIR_RESO,
        label: "VIR_RESO",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_VIR_MIC_1,
        label: "VIR M1",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 2_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_VIR_MIC_1_X,
        label: "VIR M1X",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_VIR_MIC_1_Z,
        label: "VIR M1Z",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_VIR_MIC_2,
        label: "VIR M2",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 2_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_VIR_MIC_2_X,
        label: "VIR M2X",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 2_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_VIR_MIC_2_Z,
        label: "VIR M2Z",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_VIR_BLEND,
        label: "VIR BLEND",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: -100_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODEL_PRESENCE,
        label: "MDL PRE",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODEL_DEPTH,
        label: "MDL DEP",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_POSITION,
        label: "RVB POS",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_ENABLE,
        label: "RVB POWER",
        kind: ParameterKind::Switch,
        default: 1_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_MODEL,
        label: "RVB MODEL",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 5_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING1_TIME,
        label: "RVB S1 T",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING1_PREDELAY,
        label: "RVB S1 P",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 500_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING1_COLOR,
        label: "RVB S1 C",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: -10_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING1_MIX,
        label: "RVB S1 M",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING2_TIME,
        label: "RVB S2 T",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING2_PREDELAY,
        label: "RVB S2 P",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 500_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING2_COLOR,
        label: "RVB S2 C",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: -10_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING2_MIX,
        label: "RVB S2 M",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING3_TIME,
        label: "RVB S3 T",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING3_PREDELAY,
        label: "RVB S3 P",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 500_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING3_COLOR,
        label: "RVB S3 C",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: -10_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING3_MIX,
        label: "RVB S3 M",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING4_TIME,
        label: "RVB S4 T",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING4_PREDELAY,
        label: "RVB S4 P",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 500_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING4_COLOR,
        label: "RVB S4 C",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: -10_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_SPRING4_MIX,
        label: "RVB S4 M",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_ROOM_TIME,
        label: "RVB RM T",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_ROOM_PREDELAY,
        label: "RVB RM P",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 500_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_ROOM_COLOR,
        label: "RVB RM C",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: -10_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_ROOM_MIX,
        label: "RVB RM M",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_PLATE_TIME,
        label: "RVB PL T",
        kind: ParameterKind::Range,
        default: 5_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_PLATE_PREDELAY,
        label: "RVB PL P",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 500_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_PLATE_COLOR,
        label: "RVB PL C",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: -10_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_REVERB_PLATE_MIX,
        label: "RVB PL M",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_POST,
        label: "MOD POST",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_ENABLE,
        label: "MOD POWER",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_MODEL,
        label: "MOD MODEL",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 4_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_CHORUS_SYNC,
        label: "MOD CH S",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_CHORUS_TS,
        label: "MOD CH T",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 17_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_CHORUS_RATE,
        label: "MOD CH R",
        kind: ParameterKind::Range,
        default: 0.5_f32,
        minimum: 0.1_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_CHORUS_DEPTH,
        label: "MOD CH D",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_CHORUS_LEVEL,
        label: "MOD CH L",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_TREMOLO_SYNC,
        label: "MOD TR S",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_TREMOLO_TS,
        label: "MOD TR T",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 17_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_TREMOLO_RATE,
        label: "MOD TR R",
        kind: ParameterKind::Range,
        default: 0.5_f32,
        minimum: 0.1_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_TREMOLO_SHAPE,
        label: "MOD TR P",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_TREMOLO_SPREAD,
        label: "MOD TR D",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_TREMOLO_LEVEL,
        label: "MOD TR L",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_PHASER_SYNC,
        label: "MOD PH S",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_PHASER_TS,
        label: "MOD PH T",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 17_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_PHASER_RATE,
        label: "MOD PH R",
        kind: ParameterKind::Range,
        default: 0.5_f32,
        minimum: 0.1_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_PHASER_DEPTH,
        label: "MOD PH D",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_PHASER_LEVEL,
        label: "MOD PH L",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_FLANGER_SYNC,
        label: "MOD FL S",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_FLANGER_TS,
        label: "MOD FL T",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 17_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_FLANGER_RATE,
        label: "MOD FL R",
        kind: ParameterKind::Range,
        default: 0.5_f32,
        minimum: 0.1_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_FLANGER_DEPTH,
        label: "MOD FL D",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_FLANGER_FEEDBACK,
        label: "MOD FL F",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_FLANGER_LEVEL,
        label: "MOD FL L",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_ROTARY_SYNC,
        label: "MOD RO S",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_ROTARY_TS,
        label: "MOD RO T",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 17_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_ROTARY_SPEED,
        label: "MOD RO S",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 400_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_ROTARY_RADIUS,
        label: "MOD RO R",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 300_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_ROTARY_SPREAD,
        label: "MOD RO D",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_MODULATION_ROTARY_LEVEL,
        label: "MOD RO L",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 10_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_POST,
        label: "DLY POST",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_ENABLE,
        label: "DLY POWER",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_MODEL,
        label: "DLY MODEL",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_DIGITAL_SYNC,
        label: "DLY DG S",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_DIGITAL_TS,
        label: "DLY DG T",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 17_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_DIGITAL_TIME,
        label: "DLY DT M",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1000_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_DIGITAL_FEEDBACK,
        label: "DLY DT F",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_DIGITAL_MODE,
        label: "DLY DT O",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_DIGITAL_MIX,
        label: "DLY DT X",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_TAPE_SYNC,
        label: "DLY TA S",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_TAPE_TS,
        label: "DLY TA T",
        kind: ParameterKind::Select,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 17_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_TAPE_TIME,
        label: "DLY TA M",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1000_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_TAPE_FEEDBACK,
        label: "DLY TA F",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_TAPE_MODE,
        label: "DLY TA O",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_PARAM_DELAY_TAPE_MIX,
        label: "DLY TA X",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 100_f32,
    },
    ParameterSpec {
        id: TONEX_GLOBAL_BPM,
        label: "BPM",
        kind: ParameterKind::Range,
        default: 80_f32,
        minimum: 40_f32,
        maximum: 240_f32,
    },
    ParameterSpec {
        id: TONEX_GLOBAL_INPUT_TRIM,
        label: "TRIM",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: -15_f32,
        maximum: 15_f32,
    },
    ParameterSpec {
        id: TONEX_GLOBAL_CABSIM_BYPASS,
        label: "CABSIM",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_GLOBAL_TEMPO_SOURCE,
        label: "TEMPOS",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_GLOBAL_TUNING_REFERENCE,
        label: "TUNEREF",
        kind: ParameterKind::Range,
        default: 440_f32,
        minimum: 415_f32,
        maximum: 465_f32,
    },
    ParameterSpec {
        id: TONEX_GLOBAL_BYPASS,
        label: "BYPASS",
        kind: ParameterKind::Switch,
        default: 0_f32,
        minimum: 0_f32,
        maximum: 1_f32,
    },
    ParameterSpec {
        id: TONEX_GLOBAL_MASTER_VOLUME,
        label: "MVOL",
        kind: ParameterKind::Range,
        default: 0_f32,
        minimum: -40_f32,
        maximum: 3_f32,
    },
];
