[package]
name = "tonex-web"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tonex-application = { path = "../tonex-application", version = "0.1.0" }
tonex-domain = { path = "../tonex-domain", version = "0.1.0" }
tonex-parameters = { path = "../tonex-parameters", version = "0.1.0" }
tonex-ui-model = { path = "../tonex-ui-model", version = "0.1.0" }
tonex-settings = { path = "../tonex-settings", version = "0.1.0" }
tonex-skins = { path = "../tonex-skins", version = "0.1.0" }

[lints]
workspace = true
