#!/usr/bin/env python3
"""Generate the checked-in Rust TONEX parameter registry from the C reference."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "legacy/source/main/tonex_params.h"
SOURCE = ROOT / "legacy/source/main/tonex_params.c"
OUTPUT = ROOT / "rust/crates/tonex-parameters/src/generated.rs"


def parameter_names() -> list[str]:
    text = HEADER.read_text(encoding="utf-8")
    block = re.search(r"enum TonexParameters\s*\{(.*?)\};", text, re.S)
    if block is None:
        raise RuntimeError("TonexParameters enum was not found")
    return re.findall(r"\b(TONEX_(?:PARAM|GLOBAL)_[A-Z0-9_]+)\b", block.group(1))


def parameter_rows() -> list[tuple[str, str, str, str, str]]:
    text = SOURCE.read_text(encoding="utf-8")
    table = re.search(
        r"TonexParameters\[TONEX_GLOBAL_LAST\]\s*=\s*\{(.*?)\n\};", text, re.S
    )
    if table is None:
        raise RuntimeError("TonexParameters table was not found")
    return re.findall(
        r'\{\s*([-0-9.]+),\s*([-0-9.]+),\s*([-0-9.]+),\s*"([^"]+)",'
        r"\s*MODELLER_PARAM_TYPE_(SWITCH|SELECT|RANGE)",
        table.group(1),
    )


def rust_float(value: str) -> str:
    return f"{value}_f32"


def render() -> str:
    names = parameter_names()
    if names[-1] != "TONEX_GLOBAL_LAST":
        raise RuntimeError("TONEX_GLOBAL_LAST must terminate the enum")
    rows = parameter_rows()
    if len(rows) != len(names) - 1:
        raise RuntimeError(
            f"enum/table mismatch: {len(names) - 1} values, {len(rows)} rows"
        )

    sentinel = names.index("TONEX_PARAM_LAST")
    lines = [
        "// @generated by tools/generate-tonex-parameters.py; do not edit.",
        f"pub const PARAMETER_COUNT: u16 = {sentinel};",
        f"pub const GLOBAL_FIRST: u16 = {sentinel + 1};",
        f"pub const GLOBAL_END: u16 = {len(names) - 1};",
        "",
    ]
    for index, name in enumerate(names[:-1]):
        if index == sentinel:
            lines.append(f"pub const {name}: u16 = {index};")
            continue
        lines.append(
            f"pub const {name}: ParameterId = ParameterId::from_generated({index});"
        )

    lines.extend(
        [
            "",
            f"pub(crate) const SPECS: [ParameterSpec; {len(rows) - 1}] = [",
        ]
    )
    for index, ((default, minimum, maximum, label, kind), name) in enumerate(
        zip(rows, names[:-1], strict=True)
    ):
        if index == sentinel:
            continue
        lines.extend(
            [
                "    ParameterSpec {",
                f"        id: {name},",
                f'        label: "{label}",',
                f"        kind: ParameterKind::{kind.title()},",
                f"        default: {rust_float(default)},",
                f"        minimum: {rust_float(minimum)},",
                f"        maximum: {rust_float(maximum)},",
                "    },",
            ]
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"{OUTPUT} is stale; run {Path(__file__).name}")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
